spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.web=info
logging.level.org.springframework.security=warn
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
toss.payment.secret-key=${TOSS_PAYMENT_SECRET_KEY}
stockfish.path=${STOCKFISH_PATH:/app/data/stockfish}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
chess.pgn.path=${CHESS_PGN_PATH:/app/data/AJ-OTB-PGN-001.pgn}
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}
admin.email=${ADMIN_EMAIL}
chess.data-init.mode=CSV_TO_DB
chess.data-init.csv-dir=${CHESS_CSV_PATH:/app/data/csv}